package ru.vp.error

enum class ExitCode(val code: Int) {
    SUCCESS(0),
    INVALID_CLI_ARGS(10),
    CONFIG_NOT_READABLE(11),
    INVALID_YAML(12),
    INVALID_CONFIG_SCHEMA(13),
    INVALID_DATE_RANGE(14),
    INVALID_OPTION_VALUE(15),
    OUTPUT_DIR_EXISTS(20),
    FILESYSTEM_ERROR(21),
    INVALID_OUTPUT_PATH(22),
    AUTHENTICATION_FAILED(30),
    PERMISSION_DENIED(31),
    ENDPOINT_NOT_FOUND(32),
    USER_NOT_FOUND(33),
    NON_CSV_RESPONSE(34),
    NETWORK_ERROR(40),
    SERVER_ERROR(41),
    ARCHIVE_EXISTS(50),
    ARCHIVE_ERROR(51),
    INTERNAL_ERROR(99),
}
